services:
  - type: web
    name: onion-leaves-ai
    env: python
    buildCommand: ""
    installCommand: |
      pip install torch==2.0.1+cpu torchvision==0.15.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu
      pip install fastapi==0.116.1 uvicorn==0.35.0 python-multipart==0.0.20 numpy==1.24.4 ultralytics==8.1.25 pusher==3.3.3
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000